// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBjs2N0kCv4Ronf_FLuDV9Aqqo9cy9s1To',
    appId: '1:278500035958:web:d374368e1a348258427e57',
    messagingSenderId: '278500035958',
    projectId: 'test-3709b',
    authDomain: 'test-3709b.firebaseapp.com',
    storageBucket: 'test-3709b.appspot.com',
    measurementId: 'G-NLG053071L',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCenU8SlF5xZFVXoy6NCWrxrO76uviM9EA',
    appId: '1:278500035958:android:652c0cf23d513bd3427e57',
    messagingSenderId: '278500035958',
    projectId: 'test-3709b',
    storageBucket: 'test-3709b.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBjRMTQJVddxNCwWRZk-Ua05wWKKgtU9vQ',
    appId: '1:278500035958:ios:296c696f66a156b5427e57',
    messagingSenderId: '278500035958',
    projectId: 'test-3709b',
    storageBucket: 'test-3709b.appspot.com',
    iosBundleId: 'net.iceice666.flattube',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBjRMTQJVddxNCwWRZk-Ua05wWKKgtU9vQ',
    appId: '1:278500035958:ios:46bd75ecf2f21c15427e57',
    messagingSenderId: '278500035958',
    projectId: 'test-3709b',
    storageBucket: 'test-3709b.appspot.com',
    iosBundleId: 'net.iceice666.flattube.RunnerTests',
  );
}
